server:
  grpc:
    addr: :9000
    timeout: 1s
  http:
    addr: :8000
    timeout: 1s
#trace:
#  endpoint: http://jaeger:14268/api/traces
#sentry:
#  dsn: http://sentry:8999
data:
  relational:
    dialect: postgres
    host: postgres
    port: 5432
    user: kratos
    password: kratos-password
    dbname: kratos
    schema: kratos
    ssl_mode: disable
jwks:
  url: http://keycloak:8080/auth/realms/kratos/protocol/openid-connect/certs
  refresh_interval: 3600s
  refresh_rate_limit: 300s
  refresh_timeout: 10s
business:
