version: "3.9"

services:

  kratos-template:
    build:
      context: .
      dockerfile: Dockerfile
    image: kratos-template:v0.0.1
    volumes:
      - ./configs-dc:/data/conf
    ports:
      - "9000:9000"
      - "8000:8000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: kratos-password
      POSTGRES_DB: kratos
    volumes:
      - kratos:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

volumes:
  kratos:
