// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/timurkash/kratos-layout/internal/outside/data/ent/migrate"

	"github.com/timurkash/kratos-layout/internal/outside/data/ent/kratos"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Kratos is the client for interacting with the Kratos builders.
	Kratos *KratosClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Kratos = NewKratosClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Kratos: NewKratosClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Kratos: NewKratosClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Kratos.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Kratos.Use(hooks...)
}

// KratosClient is a client for the Kratos schema.
type KratosClient struct {
	config
}

// NewKratosClient returns a client for the Kratos from the given config.
func NewKratosClient(c config) *KratosClient {
	return &KratosClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `kratos.Hooks(f(g(h())))`.
func (c *KratosClient) Use(hooks ...Hook) {
	c.hooks.Kratos = append(c.hooks.Kratos, hooks...)
}

// Create returns a create builder for Kratos.
func (c *KratosClient) Create() *KratosCreate {
	mutation := newKratosMutation(c.config, OpCreate)
	return &KratosCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Kratos entities.
func (c *KratosClient) CreateBulk(builders ...*KratosCreate) *KratosCreateBulk {
	return &KratosCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Kratos.
func (c *KratosClient) Update() *KratosUpdate {
	mutation := newKratosMutation(c.config, OpUpdate)
	return &KratosUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *KratosClient) UpdateOne(k *Kratos) *KratosUpdateOne {
	mutation := newKratosMutation(c.config, OpUpdateOne, withKratos(k))
	return &KratosUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *KratosClient) UpdateOneID(id int) *KratosUpdateOne {
	mutation := newKratosMutation(c.config, OpUpdateOne, withKratosID(id))
	return &KratosUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Kratos.
func (c *KratosClient) Delete() *KratosDelete {
	mutation := newKratosMutation(c.config, OpDelete)
	return &KratosDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *KratosClient) DeleteOne(k *Kratos) *KratosDeleteOne {
	return c.DeleteOneID(k.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *KratosClient) DeleteOneID(id int) *KratosDeleteOne {
	builder := c.Delete().Where(kratos.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &KratosDeleteOne{builder}
}

// Query returns a query builder for Kratos.
func (c *KratosClient) Query() *KratosQuery {
	return &KratosQuery{
		config: c.config,
	}
}

// Get returns a Kratos entity by its id.
func (c *KratosClient) Get(ctx context.Context, id int) (*Kratos, error) {
	return c.Query().Where(kratos.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *KratosClient) GetX(ctx context.Context, id int) *Kratos {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *KratosClient) Hooks() []Hook {
	return c.hooks.Kratos
}
