// Code generated by entc, DO NOT EDIT.

package kratos

const (
	// Label holds the string label denoting the kratos type in the database.
	Label = "kratos"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the kratos in the database.
	Table = "kratos"
)

// Columns holds all SQL columns for kratos fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
