server:
  grpc:
    addr: :9000
    timeout: 1s
  http:
    addr: :8000
    timeout: 1s
  jwks:
    url: http://localhost:8080/auth/realms/kratos/protocol/openid-connect/certs
    refresh_interval: 3600s
    refresh_rate_limit: 300s
    refresh_timeout: 10s
business:
data:
  relational:
    dialect: postgres
    host: localhost
    port: 5432
    user: kratos
    password: kratos-password
    dbname: kratos
    schema: kratos
    ssl_mode: disable
#trace:
#  endpoint: http://localhost:14268/api/traces
