server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
trace:
  endpoint: http://localhost:14268/api/traces
sentry:
  dsn: http://localhost:8999
data:
  relational:
    host: localhost
    port: 5432
    user: kratos
    password: kratos-password
    dbname: kratos
    ssl_mode: disable
