server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  relational:
    host: localhost
    port: 5432
    user: kratos
    password: kratos-password
    dbname: kratos
    ssl_mode: disable
  redis:
    host: localhost
    port: 6379
    read_timeout: 0.2s
    write_timeout: 0.2s
