@startuml

package Service {
    [Conf] as conf #lightgray
    [Logger] as logger #lightgray
    component Repo as repo {
        [Data] as data
    }
    [UseCase] as uc
    [Service] as service
    rectangle Server as server {
        [GrpcServer] as grpc
        [HttpServer] as http
    }
    [App] as app
    [Jaeger] as trace #ddd
    [Sentry] as log #ddd
    note "Stabs generated\n from proto" as stabs_note
    note "For metrics" as http_note
}
[Jaeger]
[Sentry]

database Postgres
data -d-> Postgres
trace ..> Jaeger
log ..> Sentry

conf <-- data
conf <-- server
conf <-- trace
conf <-- log

data -[hidden]- repo
repo <-- uc
uc <-- service
service <-- grpc
service <-- http
grpc <-- app
http <-- app

service - stabs_note
http -- http_note

@enduml
